# Переведено Dimianas#4303 (2p2v.org)
# В этом сообщении вы можете добавлять так-же свою информацию
message:
  - '&7-----------------------------------------------------'
  - '&6%worldstats_players% &3player(s) уникальных игроков на севрере за всё время.'
  - '&3Серверу уже &6%years% лет, %months% месяцев, %days% дней. &3Мир занимает уже &6%worldstats_filesizespoof% GB'
  - '&7-----------------------------------------------------'
# %fileSize_spoof% for spoofed filesize
filesizeupdate_in_ticks: 72000
spoofsize: 0 # Сколько вы хотите накрутить к уже существующему объёму мира (Измерение в гигабайтах)

# Тут путь к вашим мирам что-бы полагин мог измерять их вес и данные
Worlds:
  - "./world/region"
  - "./world_nether/DIM-1/region"
  - "./world_the_end/DIM1/region"
  
  
# Всё что вам пригодится: 

# %worldstats_filesize% - получает размер указанных файлов
# %worldstats_filesizespoof% - получает размер указанных файлов, вместе с накрученным весом мира
# %worldstats_players% - уникальных игроков на сервере
# Дата создания мира:
# %years% - лет
# %months% - месяцев
# %days% - дней